##Day13 Tasks:

->Python program to create arrays with all the available datatypes in numpy


In [25]:
import numpy as np
#Integer type
a = np.array([1, 2, 3, 4], dtype = 'int_')
print(a,"\t\t\t\t",a.dtype)

#Float type:
f = np.array([6.6, 7.7, 8.8, 8.8], dtype = 'float_')
print(f,"\t\t\t",f.dtype)

#String type:
s = np.array(['N', 'E', 'C'], dtype = 'S')
print(s,"\t\t\t",s.dtype)

#Boolean type:
b = np.array([False, True, True, False], dtype = 'bool_')
print(b,"\t\t",b.dtype)

#Complex type:
c = np.array([1+5j, 2+2j, 5+1.1j, 7+5.1j], dtype = 'complex_')
print(c,"\t",c.dtype)

#Object type:
o = np.array([[11, 18], [51, 32], [5.1, 7.1], ['Dolby', 'dts-hd']], dtype = 'O')
print(o,"\t\t\t",o.dtype)

#Unicode type:
u = np.array([3, 5, 8, 2], dtype = 'U')
print(u,"\t\t\t",u.dtype)

#Unsigned type:
z = np.array([1, 2, 3, 4], dtype = 'uint8')
print(z,"\t\t\t\t",z.dtype)


[1 2 3 4] 				 int32
[6.6 7.7 8.8 8.8] 			 float64
[b'N' b'E' b'C'] 			 |S1
[False  True  True False] 		 bool
[1.+5.j  2.+2.j  5.+1.1j 7.+5.1j] 	 complex128
[[11 18]
 [51 32]
 [5.1 7.1]
 ['Dolby' 'dts-hd']] 			 object
['3' '5' '8' '2'] 			 <U1
[1 2 3 4] 				 uint8
